GET http://localhost:3001/select1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJoZGphaGhqYWRAbWFpbC5ydSIsImlhdCI6MTY3MDU3MzEyNiwiZXhwIjoxNjcwNTczMTU2fQ.SUwYqNvzZbfRGhZ_TDV6wUfSsQryjuJvLWPs7r-sLMo

###

POST http://localhost:3001/login
Content-Type: application/json;

{"email":"Hello","password":"password"}